apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-demo
spec:
  resources:
    - name: git-source
      type: git
    - name: reg-target
      type: image
  tasks:
    - name: build-docker-image-from-git-source
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/tekton-demo-git-rep
      resources:
        inputs:
          - name: tekton-demo-git-rep
            resource: tekton-demo-git-rep
        outputs:
          - name: tekton-demo-img-reg
            resource: tekton-demo-img-reg
