apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuazhzLmJucy5jby5rciI6eyJ1c2VybmFtZSI6InRhbmdnbGUiLCJwYXNzd29yZCI6IiFKdXllMDJAIiwiZW1haWwiOiJncGt3b25AYm5zLmNvLmtyIiwiYXV0aCI6ImRHRnVaMmRzWlRvaFNuVjVaVEF5UUE9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
